name: "Rule Change Proposal"
description: Propose an update to the rulebook or governance
labels: ["rules", "proposal"]
body:
  - type: input
    id: section
    attributes: { label: Section(s) to change }
    validations: { required: true }
  - type: textarea
    id: current
    attributes: { label: Current text }
  - type: textarea
    id: proposed
    attributes: { label: Proposed text }
    validations: { required: true }
  - type: textarea
    id: rationale
    attributes: { label: Rationale & competitive impact }
    validations: { required: true }
  - type: textarea
    id: evidence
    attributes: { label: Evidence / data (optional) 
